version: "3.7"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Usman@123
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    networks:
      - s-network
    volumes:
      - postgres-f-data:/var/lib/postgresql/data

networks:
  s-network:
    driver: bridge

volumes:
  postgres-f-data: